#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# sudo not required for some system commands
for command in mount umount pacman updatedb systemctl; do
  alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
  l="ls -al" \
  lf="lfub" \
  cp="cp -iv" \
  mv="mv -iv" \
  rm="rm -vI" \
  bc="bc -ql" \
  df="df -h" \
  du="du -h" \
  free="free -m" \
  mkd="mkdir -pv"

# Colorize commands when possible.
alias \
  ls="ls -hN --color=auto --group-directories-first" \
  grep="grep --color=auto" \
  egrep="egrep -Hn --color=auto" \
  pgrep="pgrep -Hn --color=auto" \
  diff="diff --color=auto" \
  ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
  sqlite="sqlite3 -init "$XDG_CONFIG_HOME"/sqlite3/sqliterc" \
  trem="transmission-remote" \
  yt="ytfzf" \
  e="$EDITOR" \
  v="$EDITOR" \
  g="git" \
  p="pacman" \
  y="paru" \
  vote="ssh aur@aur.archlinux.org vote" \
  z="zathura"

alias \
  nvst="nvim --startuptime /tmp/startup.log -c exit && tail -100 /tmp/startup.log" \
  magit="nvim -c Neogit" \
  mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist" \
  halo_list_systemctl="systemctl list-unit-files --state=enabled" \
  zsh-update="find '$ZDOTDIR/plugins' -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q" \
  scan="hp-scan -i -r 400 -m color --pdf=zathura -o" \
  terraria="'/home/hooregi/media/games/terraria/start.sh' ''"
