#!/bin/sh

# use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# sudo not required for some system commands
for command in mount umount pacman updatedb systemctl; do
  alias $command="sudo $command"
done
unset command

# verbosity and settings we always want
alias \
  l="ls -al" \
  lf="lfcd" \
  cp="cp -iv" \
  mv="mv -iv" \
  rm="rm -vI" \
  bc="bc -ql" \
  df="df -h" \
  du="du -h" \
  free="free -m" \
  mkd="mkdir -pv"

# colorize when possible
alias \
  ls="ls -hN --color=auto --group-directories-first" \
  grep="grep --color=auto" \
  diff="diff --color=auto" \
  ip="ip -color=auto"

# abbreviate commands
alias \
  sqlite="sqlite3 -init "$XDG_CONFIG_HOME"/sqlite3/sqliterc" \
  e="$EDITOR" \
  v="$EDITOR" \
  g="git" \
  p="pacman" \
  y="paru" \
  vpn="nordvpn"

alias \
  og="vim_obsidian --index" \
  on="vim_obsidian --note" \
  oo="cd $(vim_obsidian --vault)" \
  or="vim_obsidian --review"

# miscellaneous functions
alias \
  nvst="nvim --startuptime /tmp/startup.log -c exit && tail -100 /tmp/startup.log" \
  mirror-update="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist" \
  zsh-update="find '$ZDOTDIR/plugins' -type d -exec test -e '{}/.git' ';' -print0 | xargs -0 -I {} sh -c 'echo Updating {}; git -C {} pull -q'" \
  halo_list_systemctl="systemctl list-unit-files --state=enabled" \
  terraria="'/home/${USER}/media/games/Terraria/start.sh' ''"
