#!/bin/zsh

# Adds `~/.local/bin` to $PATH recursively
typeset -U path
path+=(~/.local/bin{,/**/*(N/)})
unsetopt PROMPT_SP

# default programs:
export TERMINAL="st"
export TERMINAL_PROG="st"
export EDITOR="nvim"
export BROWSER="librewolf"
export READER="zathura"
export FILE="lf"

# ~/ clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="-"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export DEBUGINFOD_URLS="https://debuginfod.elfutils.org/"
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export GOPATH="$XDG_DATA_HOME/go"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export OPAMROOT="$XDG_DATA_HOME/opam"
export PYTHONPYCACHEPREFIX="$XDG_CACHE_HOME/python"
export PYTHONUSERBASE="$XDG_DATA_HOME/python"
export PYENV_ROOT="$XDG_DATA_HOME/pyenv"
eval "$(pyenv init --path)"
export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
export IPYTHONDIR="$XDG_CONFIG_HOME/jupyter"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"
export R_LIBS_USER="$XDG_DATA_HOME/R/library"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export HISTFILE="$XDG_DATA_HOME:-$HOME/history"
export FFMPEG_DATADIR="$XDG_DATA_HOME/ffmpeg"
export SSB_HOME="$XDG_DATA_HOME/zoom"

# other program settings:
export MANPAGER="nvim +Man!"
export MANWIDTH="999"
export SUDO_ASKPASS="$HOME/.local/bin/dmenu_pass"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export LESS="-R"
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
export QT_QPA_PLATFORMTHEME="gtk2" # have QT use QTK2 theme
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR=1
export MOZ_USE_XINPUT2="1" # mozilla smooth scrolling/touchpads.

# Start graphical server on user's current tty if not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
