#!/bin/zsh

# Adds `~/.local/bin` to $PATH recursively
typeset -U path
path+=(~/.local/bin{,/**/*(N/)})
unsetopt PROMPT_SP

# default programs:
export TERMINAL="st"
export EDITOR="nvim"
export BROWSER="brave"
export READER="zathura"
export FILE="lf"

# ~/ clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="-"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export DEBUGINFOD_URLS="https://debuginfod.elfutils.org/"
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
export DOCKER_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/docker"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/npm/npmrc"
export NODE_REPL_HISTORY="${XDG_DATA_HOME:-$HOME/.local/share}/node_repl_history"
export OPAMROOT="${XDG_DATA_HOME:-$HOME/.local/share}/opam"
export PYENV_ROOT="${XDG_DATA_HOME:-$HOME/.local/share}/pyenv"
eval "$(pyenv init --path)"
export IPYTHONDIR="${XDG_CONFIG_HOME:-$HOME/.config}/jupyter"
export JUPYTER_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/jupyter"
export R_LIBS_USER="${XDG_DATA_HOME:-$HOME/.local/share}/R/library"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export SQLITE_HISTORY="${XDG_DATA_HOME:-$HOME/.local/share}/sqlite_history"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export FFMPEG_DATADIR="${XDG_DATA_HOME:-$HOME/.local/share}/ffmpeg"
export SSB_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/zoom"

# other program settings:
export MANPAGER="nvim +Man!"
export MANWIDTH="999"
export SUDO_ASKPASS="$HOME/.local/bin/dmenu_pass"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export LESS="-R"
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
export QT_QPA_PLATFORMTHEME="gtk2" # have QT use QTK2 theme
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR=1
export MOZ_USE_XINPUT2="1" # mozilla smooth scrolling/touchpads.

# This is the list for lf icons:
export LF_ICONS="di=:\
fi=:\
tw=:\
ow=:\
ln=:\
or=:\
ex=:\
*.txt=:\
*.mom=:\
*.me=:\
*.ms=:\
*.png=:\
*.webp=:\
*.ico=:\
*.jpg=:\
*.jpe=:\
*.jpeg=:\
*.gif=:\
*.svg=:\
*.tif=:\
*.tiff=:\
*.xcf=:\
*.html=:\
*.xml=:\
*.gpg=:\
*.css=:\
*.pdf=:\
*.djvu=:\
*.epub=:\
*.csv=:\
*.xlsx=:\
*.tex=:\
*.md=:\
*.r=:\
*.R=:\
*.rmd=:\
*.Rmd=:\
*.m=:\
*.mp3=:\
*.opus=:\
*.ogg=:\
*.m4a=:\
*.flac=﴾:\
*.wav=﴾:\
*.mkv=:\
*.mp4=:\
*.webm=:\
*.mpeg=:\
*.avi=:\
*.mov=:\
*.mpg=:\
*.wmv=:\
*.m4b=:\
*.flv=:\
*.zip=:\
*.rar=:\
*.7z=:\
*.tar.gz=:\
*.z64=:\
*.v64=:\
*.n64=:\
*.gba=:\
*.nes=:\
*.gdi=:\
*.1=:\
*.nfo=:\
*.info=:\
*.log=:\
*.iso=:\
*.img=:\
*.bib=:\
*.ged=:\
*.part=:\
*.torrent=:\
*.config=:\
*.cpp=:\
*.bak=:\
*.db=:\
*.diff=:\
*.dockerfile=:\
*.go=:\
*.hs=:\
*.jar=:\
*.java=:\
*.js=:\
*.json=:\
*.lua=:\
*.ml=:\
*.pl=:\
*.py=:\
*.rs=:\
*.sql=:\
*.vim=:\
"

if pacman -Qs libxft >/dev/null 2>&1; then
	# Start graphical server on user's current tty if not already running.
	[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
else
  echo "\033[31mIMPORTANT\033[0m: Note that \033[32m\`libxft\`\033[0m must be installed.
Please run:
	\033[32mpacman -S libxft\033[0m
Afterwards, you may start the graphical server by running \`startx\`."
fi
