#!/bin/sh

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
  . "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
  . "$HOME/.xprofile"
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

#eval $(ssh-agent)
#exec dwm

if [ -z "$SSH_AUTH_SOCK" ]; then
  eval "$(ssh-agent -s)"
fi

while :; do
  dwm || break
done

# cleanup on session end
ssh-agent -k
