#!/bin/sh

xrandr --dpi 141.856
xrdb "$XDG_CONFIG_HOME/x11/xresources" &
xrdbpid=$!
rescrs &

autostart="picom
dunst
dwmblocks
unclutter
solaar -w hide
pactl load-module module-switch-on-connect"

echo "$autostart" | while IFS= read -r program; do
  pidof -sx "$program" || $program &
done >/dev/null 2>&1

# ensure that xrdb finished running before starting the WM
[ -n "$xrdbpid" ] && wait "$xrdbpid"
