#!/bin/sh
while read -r file; do
  case "$1" in
  "w") setbg "$file" & ;;
  "c")
    [ -z "$destdir" ] && destdir="$(sed "s/#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs | awk '{print $2}' | dmenu -l 20 -i -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
    [ ! -d "$destdir" ] && notify-send -a "Image Viewer" "$destdir is not a directory, cancelled." && exit
    cp "$file" "$destdir" && notify-send -a "Image Viewer" -i "$(readlink -f "$file")" " $file copied to $destdir." &
    ;;
  "m")
    [ -z "$destdir" ] && destdir="$(sed "s/#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs | awk '{print $2}' | dmenu -l 20 -i -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
    [ ! -d "$destdir" ] && notify-send -a "Image Viewer" "$destdir is not a directory, cancelled." && exit
    mv "$file" "$destdir" && notify-send -a "Image Viewer" -i "$(readlink -f "$file")" "󰪹 $file moved to $destdir." &
    ;;
  "r")
    magick "$file" -rotate 90 "$file"
    ;;
  "R")
    magick "$file" -rotate -90 "$file"
    ;;
  "f")
    magick "$file" -flop "$file"
    ;;
  "y")
    readlink -f "$file" | tr -d '\n' | xclip -selection clipboard &&
      notify-send -a "Image Viewer" -i "$(readlink -f "$file")" "$file copied to clipboard" &
    ;;
  "d")
    [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send -a "Image Viewer" -i "$(readlink -f "$file")" "$file deleted."
    ;;
  "g")
    gimp && setsid -f gimp "$file"
    ;;
  "i")
    notify-send -a "Image Viewer" "$(exiftool -p 'Size: $FileSize$/Dimensions: $ImageSize$/Format: $FileType' "$file")"
    ;;
  esac
done
