"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  { on = "f", run = "search rg", desc = "Search files by content via ripgrep." },
  { on = "/", run = "filter --smart", desc = "Filter files." },
  { on = ["<C-s>"], run = ["hidden toggle"], desc = "Toggle the visibility of hidden files." },
  { on = ["j"], run = ["arrow 1"], desc = "Next item without wraparound." },
  { on = ["k"], run = ["arrow -1"], desc = "Previous item without wraparound." },
  { on = ["l"], run = ["plugin smart-enter", "escape --visual --select"], desc = "Enter the child directory, or open file." },
  { on = ["L"], run = "plugin smart-enter detach", desc = "Open in new window." },
  { on = ["="], run = """shell 'printf "Permissions (in mode-bits): "; read ans; chmod $ans "$@"' --block""", desc = "chmod wrapper." },
  { on = ["C"], run = """shell 'dragon-drop -x -i -T "$@"'""" },
  { on = ["S"], run = """shell 'curl -F "file=@$@" -Fsecret= 0x0.st | qrencode -o "/tmp/qrcode.png" && notify-send -a "Share" -t 60000 -i "/tmp/qrcode.png" " File piped to the QR code." && rm -f "/tmp/qrcode.png"'""", desc = "Share file via QR code." },
  { on = ["Z"], run = "plugin compress", desc = "Archive selected files." },
  { on = ["R"], run = """shell '$TERMINAL -e $SHELL -c -i \"cd $PWD && lfcd && exec $SHELL\"' --orphan --confirm """, desc = "Spawn new yazi window in CWD" },
]
