"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [1, 2, 3]
sort_by = "natural"
linemode = "size"

[preview]
wrap = "yes"
max_width = 1000
max_height = 1500

[opener]
open = [{ run = 'yz_open "$@"', block = true, desc = "Open" }]
edit = [{ run = 'mimeopen --ask "$@"', block = true, desc = "Edit" }]

[open]
rules = [
  { name = "*/", use = ["open", "reveal"] },
  { mime = "*", use = ["open", "edit", "extract"] },
]

[plugin]
prepend_previewers = [
  # general
  { mime = "audio/*", run = "exifaudio" },
  # specific
  { mime = "image/xcf", run = "magick" },
  #{ mime = "*opendocument*", run = "office-preview" },
  # archives
  { mime = "application/{zip,gzip,tar,bzip,bzip2,7z-compressed,rar,xz}", run = "archive" },
]
